### ISSUE TITLE
LocalStorage

### ISSUE THREAD

**Issue by danielgek** [driftyco/ionic-storage#1]
hi, i'm updating my project from las ionic beta to the recent  rc0 and storage moved here, but LocalStorage is gone, is this on purpose ? should we use sql only now ?

**Comment by namuit** [comment]
I have the same question: the documentation isn't updated yet and, as LocalStorage, also SqlStorage is gone.

In the Ionic2 beta 11 the code was
```typescript
import {Storage, SqlStorage} from 'ionic-angular';
```
Now?

**Comment by danielgek** [comment]
you can use 
```javascript 
import { Storage } from '@ionic/storage';
```

don't forget to add ``` "@ionic/storage": "^1.0.3", ``` to package.json

but you still don't get LocalStorage or SqlStorage types

**Comment by danielgek** [comment]
and no getJson/setJson methods

**Comment by namuit** [comment]
I already updated the code but I was hoping I was wrong and it was missing something with LocalStorage and SqlStorage. I'm rewriting my provider with getJson/setJson (I was using them).

By the way thanks a lot!

**Comment by appyourself** [comment]
do we need this

`var sqliteDriver = CordovaSQLiteDriver['default'];` ?

**Comment by zakton5** [comment]
Yes this is a huge issue for me. I relied heavily on ```SqlStorage``` and now it is gone. My app cannot function without it.

**Comment by ktross** [comment]
@zakton5 

It now automatically chooses the storage method. Taken from the driftyco/ionic-storage comments:

> Storage is an easy way to store key/value pairs and other complicated data in a way that uses a variety of storage engines underneath. Currently, Storage uses localforage underneath to abstract away the various storage engines while still providing a simple API.
> 
> When running natively, Storage will prioritize using SQLite, as it's one of the most stable and widely used file-based databases, and avoids some of the pitfalls of things like localstorage that the OS can decide to clear out in low disk-space situations.
> 
> When running in the web or as a Progressive Web App, Storage will attempt to use IndexedDB, WebSQL, and localstorage, in that order.

You should be able to do something like this as a temporary workaround:

`
this.storage = new Storage();
this.storage._db.setDriver([this.storage._db.LOCALSTORAGE]);
`

You can pass the following options:

* this.storage._db.INDEXEDDB
* this.storage._db.WEBSQL
* this.storage._db.LOCALSTORAGE

Check out https://github.com/driftyco/ionic-storage/blob/master/src/storage.ts for more information.

**Comment by zakton5** [comment]
Thanks for that! That helps a bit but my main problem is that ```query``` no longer exists on _db. How do I run actual SQL queries against the DB?

**Comment by aggarwalankush** [comment]
@zakton5 storage currently doesn't have query method. I opened a issue regarding that and it's added in rc1 milestone. You can track it here https://github.com/driftyco/ionic/issues/8269.

**Comment by zakton5** [comment]
@aggarwalankush Thanks for pointing me in the right direction!

**Comment by mlynch** [comment]
Hey all. First of all, we're very sorry about not communicating that we'd be making this change. RC.0 came up on us fast and we rushed this out.

Secondly, we moved to `Storage` as a simple abstraction so you didn't have to explicitly specify which engine you wanted to use. We'd pick the "best" one available (with configuration options to override those choices), and expose a simple key value API that would Just Work.

In that case, you don't need to think about LocalStorage.

I've just updated the readme that walks through how to use `Storage`: https://github.com/driftyco/ionic-storage/blob/master/README.md

Please feel free to file more issues or ask any questions!
