### ISSUE TITLE
Ionic Storage - QuotaExceededError - error - 

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-storage#10]
_From @bimal72 on October 3, 2016 10:10_

Hello, 
I was using **SqlStorage** in beta 11. My requirement is simple, storing key-value pair.
I have just changed to @ionic/storage.
As per its documents, it says that 
**A simple key-value Storage module for Ionic apps based on LocalForage, with out-of-the-box support for SQLite. This utility makes it easy to use the best storage engine available without having to interact with it directly. Currently the ordering is SQLite, IndexedDB, WebSQL, and LocalStorage.**

Hence I have deployed it in one of my device for testing and I found that it is throwing 
**EXCEPTION: Uncaught (in promise): QuotaExceededError: An attempt was made to add something to storage that exceeded the quota.**

I am assuming it is using LocalStorage somehow. In beta 11 it was working very well using 
```
new Storage(SqlStorage, { name: 'my_app' });
```

_Copied from original issue: driftyco/ionic#8426_

**Comment by bimal72** [comment]
I am facing this issue on android 4.2.2

**Comment by bimal72** [comment]
@jgw96  Please look in this issue, as I have used this in my products

**Comment by mlynch** [comment]
Try 1.1.6 and use the sqlite engine.

**Comment by bimal72** [comment]
@mlynch 

Thanks, this is working fine now. But after getting this @ionic/storage 1.1.6 and latest cordova-sqlite plugin, I am facing now another serious issue.
In my main app.component.ts , in platform ready, I am accessing 
storage.get(key);
It is giving my null.
After putting console log, I found following sequence...
```
getting data for.... env
main.js:29 DEVICE READY FIRED AFTER 697 ms
main.js:30 getting data for.... introShown
main.js:29 Ionic Storage driver: cordovaSQLiteDriver

main.js:30 setting data for.... introShown  value... true
SQLitePlugin.js:175 OPEN database: _ionicstorage
SQLitePlugin.js:106 new transaction is waiting for open operation
SQLitePlugin.js:179 OPEN database: _ionicstorage - OK
SQLitePlugin.js:80 DB opened: _ionicstorage
```
It seems that database is opening after my accessing storage key.
