### ISSUE TITLE
Storage with Ionic 3.1.0?

### ISSUE THREAD

**Issue by nicksmithr** [driftyco/ionic-storage#102]
I'm getting an error `"No Provider for Storage!"`, and when npm install'ing the new `package.json` for 3.1.0, there are unmet dependencies for `Angular 4.0.2`

Maybe I'm doing something wrong, but I'm following the docs.

**Comment by NoNameProvided** [comment]
`No Provider for Storage` means you haven't added the needed config in app.modules. Please check to the docs.

**Comment by nicksmithr** [comment]
@NoNameProvided Hm, okay. I have followed the docs step-by-step so a little confused.

In my `app.module.ts` I am importing the module `import { IonicStorageModule } from '@ionic/storage'`. I am then placing `IonicStorageModule.forRoot(),` in imports. I have installed `"@ionic/storage": "^2.0.0",`. And in a page I am using `import { Storage } from '@ionic/storage';.

Is there any further set up required? Possibly for Lazy Loading components?

**Comment by nicksmithr** [comment]
When running `npm install @ionic-storage`
```
├── UNMET PEER DEPENDENCY @angular/common@4.0.2
├── UNMET PEER DEPENDENCY @angular/compiler@4.0.2
├── UNMET PEER DEPENDENCY @angular/core@4.0.2
├── UNMET PEER DEPENDENCY @angular/platform-browser@4.0.2
├── UNMET PEER DEPENDENCY @angular/platform-browser-dynamic@4.0.2
└── @ionic/storage@2.0.1
```

**Comment by MTechDE** [comment]
Looks like you have a problem with another plugin because the storage itself don't need Angular

```json
  "peerDependencies": {
    "@angular/core": "*",
    "rxjs": "*"
  }
```

Can you post your package.json?

**Comment by nicksmithr** [comment]
@MTechDE I think it was this. I started a fresh project, not with npm updating, and all is working. Thanks for your time!
