### ISSUE TITLE
Add logging to indicate the storage engine in use

### ISSUE THREAD

**Issue by ghenry22** [driftyco/ionic-storage#11]
At the moment there is no indication as to the storage engine that is in use.  It would be good to have at least a console log statement that say something like "ionic.storage engine in use is SQLITE".

The previous storage/sqlstorage implementation used to do something along these lines.

**Comment by ghenry22** [comment]
The ability to set a "preferred" storage engine if available would also be nice as it would make things more predictable.  For example maybe I just want to use localstorage whenever it is available, if it's not then fall back through the standard preferred order

**Comment by mlynch** [comment]
Added logging in 1.1.6. Thanks. Will consider the other feature for our upcoming config stuff
