### ISSUE TITLE
Cannot load localforage-cordovasqlitedriver behind a firewall

### ISSUE THREAD

**Issue by timowolf** [driftyco/ionic-storage#12]
The dependency localforage-cordovasqlitedriver cannot be loaded within enterprise setting due to closed ports and firewalls. A git clone can typically not access github directly. 

Please use a npm dependency instead, as this is resolved via local enterprise caching repositories.

**Comment by ggirou** [comment]
I have the same issue, please publish a new version of [localForage-cordovaSQLiteDriver](https://github.com/driftyco/localForage-cordovaSQLiteDriver)

**Comment by mlynch** [comment]
Hey, going to be moving this over to the official plugin now that typings are available. Stand by

**Comment by mlynch** [comment]
Fixed, use 1.1.6. Thanks

**Comment by timowolf** [comment]
Thanks, LGTM 👍
