### ISSUE TITLE
Bundle dev failed: localforage.js does not export default.

### ISSUE THREAD

**Issue by kleeb** [driftyco/ionic-storage#13]
During bundle dev started ... I am getting:

`Error: 
Module .../node_modules/localforage/dist/localforage.js does not export default (imported by .../node_modules/@ionic/storage/es2015/storage.js)
    at Module.trace (.../node_modules/rollup/dist/rollup.js:7706:29)
    at ModuleScope.findDeclaration (.../node_modules/rollup/dist/rollup.js:7329:22)`

**Comment by kleeb** [comment]
Solution:

modify rollup.config.js in node_modules/@ionic/app-scripts/config:

`plugins: [
ngTemplate(),
commonjs({
    include: [
    'node_modules/rxjs/**',
    'node_modules/angularfire2/**',
    'node_modules/firebase/**',
    'node_modules/@ionic/storage/**',
    'node_modules/localforage/**'
    ],
    namedExports: {
    'node_modules/angularfire2/node_modules/firebase/firebase.js': ['initializeApp', 'auth', 'database'],
    'node_modules/angularfire2/node_modules/firebase/firebase-browser.js': ['initializeApp', 'auth', 'database']
    
    }
}),
nodeResolve({
  module: true,
  jsnext: true,
  main: true,
  browser: true,
  extensions: ['.js']
})`

**Comment by dmastag** [comment]
Thanks @kleeb you helped me fix this.
Just formatting in case someone has difficulties reading it

```
    plugins: [
        ...
        builtins(), // builtins is now used in
        commonjs({
            include: [
                'node_modules/rxjs/**',
                'node_modules/firebase/**',
                'node_modules/angularfire2/**',
                'node_modules/@ionic/storage/**',
                'node_modules/localforage/**'
            ],
```

**Comment by luckylooke** [comment]
I end up here by same error in my project, not relating to ionic, but your answers fixed my issue as well... so just adding that commonjs is `@rollup/plugin-commonjs`, so just import it on top
```js
import commonjs from '@rollup/plugin-commonjs';
```
thank you guys for coop 🙏
