### ISSUE TITLE
Storage constructor makes async initialization

### ISSUE THREAD

**Issue by mnasyrov** [driftyco/ionic-storage#19]
Version 1.1.6 introduces async defining a driver inside Storage constructor. 
It breaks using Storage in sync context (e.g. tests) and there is no way to reuse an initialization promise to delay a work with an instance of Storage.

**Comment by mirkonasato** [comment]
The `Storage` constructor was already async before: it was calling `setDriver`. But yes some way to know for sure when it's ready would be good.

**Comment by mirkonasato** [comment]
See #20, just because there's more info there.
