### ISSUE TITLE
feat: ability to specify preferred storage type

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic-storage#22]
It would be create to have an enum passed into the Storage constructor that allows the user to specify their preferred storage type.

If their preferred storage type is not available, show a warning in the console, and then proceed to pick the next best storage option as you normally would. 

The reason why I want this is because when I am working in the browser, I would very much like to use localstorage over everything else. Especially when running `ionic serve` and debugging on chrome and changing the device types quite a lot, the IndexedDb instance resets which is a pain. Localstorage persists quite nicely in this case.

**Comment by matiasmoya** [comment]
There is a pending PR that will introduce this feature:
https://github.com/driftyco/ionic-storage/pull/6

**Comment by tcrespog** [comment]
The PR #6 has already been merged, I see the setDriver function (https://github.com/driftyco/ionic-storage/blob/master/src/storage.ts#L152):
`setDriver(engine: string) {
    this._db.setDriver(this._db.engine);
}`
However I'm not sure how to use it. In the first place it confuses me that the `engine` param is not used in the function body.
Any clarification on this?

**Comment by jgw96** [comment]
Hello @tcrespog ! I just pushed a commit to fix the issue you mentioned, sorry for the confusion.
