### ISSUE TITLE
get throwing exception

### ISSUE THREAD

**Issue by philipbrack** [driftyco/ionic-storage#24]
I am using @ionic/storage@1.1.6

Often when this code runs I get an exception.  Should this throw anything ever?

```
let local = new Storage();
local.get('isSetup') <----
```

I didn't see this on earlier version.

**Comment by philipbrack** [comment]
This is my work around to getting this to work.  Make sure the member reference is only constructed once.

```

  ionViewDidEnter() {
    this.platform.ready().then(() => {

      if (!this.local) {
        this.local = new Storage();
      }
      ....
  }
```

**Comment by mlynch** [comment]
Hi, try 1.1.7 which as a `ready` method. Thanks!
