### ISSUE TITLE
Storage's get function returns null

### ISSUE THREAD

**Issue by shuishuiafeng** [driftyco/ionic-storage#26]
Now using the latest version ionic-storage@1.1.6, and using ionic version is ionic2 rc1.
Only debugging on the device have below problem(command:ionic run android -l -c -s --device), when debugging on the computer browser is normal(command: ionic serve).
After import Storage, and set key-value pairs like below:
**storage.set('customer_id',1021);**
after the above code, add the following code:
**storage.get('customer_id').then((data)=>{
      console.log('customer_id:'+data);
});**
the issue is print customer_id's value is null. but when I click on a link to another page, then can get customer_id from storage, or when I restart, also can get correct value. only first time get value is null.

**Comment by vintage** [comment]
Same issue here. I thought that I'm loosing my mind, but first time trying to add something to the storage fails.

**Comment by vintage** [comment]
Checkout this PR https://github.com/driftyco/ionic-storage/pull/21

**Comment by aaronksaunders** [comment]
has this issue been resolved yet?

**Comment by mlynch** [comment]
Yes this should be resolved in 1.1.7

**Comment by ajdnass** [comment]
every time you see something like this:

`myFunction().then(....)`
or

`myFunction(callbackFunction());`
then myFunction is doing some asynchronous work --> so it could take some or more time to execute this function.
But JavaScript runs to completion --> it start in your first line of code and goes through your code --> means the browser does not wait until the callback of then() is called. it start the this.storage.get() function and goes on for your console.log. And at some point this.storage.get() has finished and calls the callback you defined in then()
sso you need to use like this 
` console.log('Your value is', storage.get('name'));`
