### ISSUE TITLE
Prepare for localforage v1.5 upgrade

### ISSUE THREAD

**Issue by thgreasi** [driftyco/ionic-storage#28]
We just merged localforage/localForage#611 which adds typescript typings as part of the repo and it's planned to be released (at some point) as v1.5.0.
The respective change on localforage-cordovasqlitedriver is going to be released as v1.6.0 and is currently under the [lf1.5 branch](https://github.com/thgreasi/localForage-cordovaSQLiteDriver/tree/lf1.5).

Just giving you a note about that, in order to avoid any "duplicate identifier" errors when v1.5 gets released.
Most probably, all that needs to be done is to remove the `@types/localforage` package.
I will try to keep you posted.

**Comment by jgw96** [comment]
Big thanks for the heads up @thgreasi ! We will take a look at this.

**Comment by thgreasi** [comment]
Any feedback on this? Should we proceed and release lovalforage v1.5?

**Comment by tofumatt** [comment]
Just an update that we released 1.5 which defaults to IndexedDB; @thgreasi mentioned that ionic is pinned to localForage `1.4.x` so you shouldn't be affected, but I thought I'd just post here to be sure 😄

Cheers!

**Comment by thgreasi** [comment]
Just to make this clear, the major change that affects ionic storage, is
that localforage now includes its own typings.

-- 
*Thodoris Greasidis*

**Comment by tofumatt** [comment]
Ah, fair enough. But I guess the move to IndexedDB might mean when upgrading to localForage 1.5 data will be lost, so that's something to keep in mind as well.

**Comment by mlynch** [comment]
Thanks again. We will take a look in the coming weeks. We very specifically specify storage order because mobile is super finicky, so the defaults changing shouldn't be an issue (famous last words)

**Comment by thgreasi** [comment]
> so the defaults changing shouldn't be an issue

As far I have checked this repo's code, that should be correct. While testing #78 on a newlly created --v2 app, I faced no issues.

> (famous last words)

😆
