### ISSUE TITLE
Using @ionic-storage with latest Ionic 2 Config

### ISSUE THREAD

**Issue by scottsword** [driftyco/ionic-storage#30]
I recently used the CLI to generate an Ionic 2 app, but when I try and add Ionic storage it throws an error related to the import statement. It would appear that there is some sort of issue with the new tsconfig module setting and ionic-storage.

`ParseError: 'import' and 'export' may appear only with 'sourceType: module'`

### Asset Version Info
```
"ionic-angular": "2.0.0-beta.11"
"@angular/core": "2.0.0-rc.4",
"@ionic/storage": "^1.1.6"
```

### Environment 
```
node v6.3.1
```

### TS Config
```
"module": "commonjs"
```

**Comment by gujiman** [comment]
hi,

i have the same issue. did u manage to sort it out??
