### ISSUE TITLE
Cannot read property 'name' of null

### ISSUE THREAD

**Issue by Iyashu5040** [driftyco/ionic-storage#31]
I've stored some images as Base64 strings in storage using the image URL as the key. This is effectively an image cache to save some user data while using my app. When using Ionic Serve I sometimes run into the error in the issue title. This does not happen on a device though. It also does not happen with every item.

The source function that causes this error is:

```
var promise = self._initReady().then(function () {
        var dbContext = dbContexts[self._dbInfo.name];

        if (dbContext && dbContext.dbReady) {
            return dbContext.dbReady;
        }
});
```

That self._dbInfo is null and the accessing the name property causes an exception.

I've handled the promise rejection in my code so the app isn't crashing but now those storage items are inaccessible.

**Comment by mlynch** [comment]
Could be related to this race condition. Fixed in #21 

Try 1.1.7 and let me know if that fixed it for you, thanks.
