### ISSUE TITLE
Delete value

### ISSUE THREAD

**Issue by cozzbie** [driftyco/ionic-storage#35]
How do I delete a certain key => value pair with this? key => null???

**Comment by mlynch** [comment]
Hey, this isn't really an issue per say so I'm closing this for now. If you have more code to share perhaps someone can help! Thanks.

**Comment by EralpB** [comment]
Wow README doesn't say how to delete a value, and this issue has been closed.

The issue is there's no code example on how to delete a key. Is there a method? Shall I set to null or undefined?

**Comment by mlynch** [comment]
Just updated the README, but for others, use `Storage.remove(key)`
