### ISSUE TITLE
Should we include a Cordova plugin when using this?

### ISSUE THREAD

**Issue by Manduro** [driftyco/ionic-storage#4]
For example, the cordova-sqlite-plugin? Or does this work without a cordova plugin?

**Comment by Iyashu5040** [comment]
+1 Unclear if we need to install sqlite plugin to enable sqlite on devices.

**Comment by ghenry22** [comment]
Some info on the docs about installing the salute plugin and also how to tell which storage engine has been chosen since it's now automatic would be nice

**Comment by mlynch** [comment]
Hi all, I've updated the README to explain when/how to add a cordova plugin for sqlite w/ this plugin: https://github.com/driftyco/ionic-storage/blob/master/README.md#installation
