### ISSUE TITLE
Failed to execute 'transaction' on 'IDBDatabase'

### ISSUE THREAD

**Issue by kesozjura** [driftyco/ionic-storage#40]
After upgrading to ionic-angular@rc.2 and ionic-storage@1.1.6 we get this error:

`Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.`

App runs on iPad on latest iOS. With ionic-storage@1.0.3 it is OK, so we had to revert to that version for now.

**Comment by falkoschumann** [comment]
Still the same issue with RC3

Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62

**Comment by mlynch** [comment]
hmm, can you try 1.1.7? I'll re-open if it's still an issue.

**Comment by kesozjura** [comment]
It works now. Thanks
