### ISSUE TITLE
Windows phone error for SQL Lite

### ISSUE THREAD

**Issue by isvaljek** [driftyco/ionic-storage#41]
When I deploy to Windows 10 mobile device I get this error on Auth0 Lock login screen:
I believe this is so, because Auth0 Auth service depends upon ionic/storage.

Exception was thrown at line 3, column 8540 in ms-appx-web://aaa.td/www/build/polyfills.js
0x800a139e - JavaScript runtime error: Uncaught (in promise): Error: SQLite plugin is not present.

**Comment by mlynch** [comment]
Thanks for the issue, auth0 doesn't depend on our plugin so this would be better on their end.
