### ISSUE TITLE
wrong typings with v1.1.6

### ISSUE THREAD

**Issue by Bouzmine** [driftyco/ionic-storage#43]
I updated my app to @ionic/storage to v1.1.6 and I can't use the `setEngine` method because it isn't present in the typings (absent in both `es5/storage.d.ts` and `es2015/storage.d.ts`). Tried installing, removing, reinstalling, etc.

**Comment by mhartington** [comment]
`setEngine` was renamed to `setDriver`

https://github.com/driftyco/ionic-storage/commit/c42d173675918f33db0cef4235ac385d9ba682ae
