### ISSUE TITLE
Property 'query' does not exist on type 'Storage'.

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-storage#45]
_From @mvsiva4u on November 15, 2016 12:25_

**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short deiscription of the problem:
if i used below sqllite to get data from sql list database
this.storage.query(sql, [data.institutionid, data.app, data.capability]);

#### What behavior are you expecting?

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks (```)
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

_Copied from original issue: driftyco/ionic-conference-app#314_

**Comment by mhartington** [comment]
From the readme.md

> If you want to perform arbitrary SQL queries and have one of the best storage options around, we recommend using the Ionic Native SQLite plugin directly. This engine no longer supports the query feature underneath as it was not portable and only worked for SQLite anyways.
