### ISSUE TITLE
Angular 2 only?

### ISSUE THREAD

**Issue by rinogo** [driftyco/ionic-storage#46]
I can't find this clearly documented anywhere in the project - this module is for Angular 2 only, and doesn't support Angular 1.x, correct?

**Comment by flakerimi** [comment]
You can see on package.json
```

 "dependencies": {
    "@angular/core": "^2.0.0",
    "@types/localforage": "0.0.30",
    "localforage": "^1.4.2",
    "localforage-cordovasqlitedriver": "^1.5.0",
    "rxjs": "5.0.0-beta.12"
  },
```

**Comment by rinogo** [comment]
Thanks!  (For those who visit this Issue and don't grok `package.json` yet, yes, this means it requires Angular 2.0)
