### ISSUE TITLE
Session storage?

### ISSUE THREAD

**Issue by alexbainbridge** [driftyco/ionic-storage#48]
Hi there, any chance that session storage could be added to this library

I think you are based on Localforage, that supports it https://github.com/localForage/localForage-sessionStorageWrapper 

Would be helpful for web based Ionic usage as has slighty more secure ways of dealing with removing authorisation credentials on session close, easily.....  

Thanks
Alex

**Comment by NoNameProvided** [comment]
I dont really see the value here, you can just use the native localstorage api which is very similar.

**Comment by alexbainbridge** [comment]
Fair enough!
