### ISSUE TITLE
Performance issue  ?

### ISSUE THREAD

**Issue by REPTILEHAUS** [driftyco/ionic-storage#52]
Im not sure why this code doesnt work, it works in a browser but on a live phone my OnInit returns nothing but if I click the button that calls the checkCookie() function it returns the cookie.. I need to display the users data after they open and close the app and I was hoping this could be achieved using ionic-storage. 

      import { Component, OnInit, NgZone } from '@angular/core';
      import { NavController } from 'ionic-angular';
      
      import { UserData } from '../../providers/user-data';
      
      import { Storage } from '@ionic/storage';
      
      
      
      @Component({
        selector: 'page-home',
        templateUrl: 'home.html'
      })
      export class HomePage implements OnInit {
      
        constructor( public ngZone: NgZone, 
                     public navCtrl: NavController,
                     public api: UserData,
                     public storage: Storage ) {  }
      
      
          ngOnInit() {
      
            this.checkCookie();
      
          }
      
          checkCookie() {
              this.storage.get('FacebookData').then((FacebookData) => {
                  alert('COOKIESET ' + JSON.stringify(FacebookData)   );
              });
          }
      
      }

**Comment by ghenry22** [comment]
Probably need to either wait for platformready to fire or wait for the DB to be opened and ready to use.  Try wrapping your checkcookie call in:

this.platform.ready().then(() => {

}

this ensures that the native platform is ready and plugins initialised.

If you still have an issue then try wrapping your call further in a 10 second time out.  If it works then it means that the database isn't ready and open when you are making your call.

I set / get a dummy value called "dbReady" into the db on startup.  When that can be successfully completed then I start my app code.

ionic-storage really needs a proper init method that returns when the db is open and ready.  It used to have this before it was split out to it's own project.

**Comment by REPTILEHAUS** [comment]
Cool your example you just posted on the bug I referenced looks like it could be a good fix.. I'll try it out later and see if it works for me but it looks pretty good

**Comment by mlynch** [comment]
Yep, use the `ready()` method, just updated the docs to reflect. Note: only available in 1.1.7 or greater.
