### ISSUE TITLE
WS error message

### ISSUE THREAD

**Issue by alexbainbridge** [driftyco/ionic-storage#53]
On RC4 / Storage 1.1.7 , if you try 

ionic serve --consolelogs

you see an error that is not actually seen in the browser console log

```
[19:52:58]  error opening ws message: {"category":"console","type":"info","data":["Ionic Storage 
            driver:","asyncStorage"]} 
```

Not sure what that is, but looks storage related. Seems to work though, even with this error message.

**Comment by mlynch** [comment]
Thanks Alex, this is a non-error with app scripts (it can't serialize that console log with the naive JSON stringify).

**Comment by josh-m-sharpe** [comment]
If it's a non-error why does it show up?  Should it be removed?

**Comment by NoNameProvided** [comment]
It is removed in the newest version of ionic-app-scripts.

**Comment by josh-m-sharpe** [comment]
I'm still seeing it.   My package.json has:
```
  "devDependencies": {
    "@ionic/app-scripts": "^1.0.0",
    "typescript": "2.0.9"
  },
```
but i'm honestly not sure I trust that to be the right version. is there a cmd-line thing I can run to get the version of app scripts that is currently being used?

**Comment by aslamj** [comment]
Mine is the same:
`
  "devDependencies": {
    "@ionic/app-scripts": "1.0.0",
    "typescript": "2.0.9"
  },`

But I see the same error:
`
[23:17:33]  error opening ws message: {"category":"console","type":"info","data":["Ionic Storage
            driver:","asyncStorage"]}
`

**Comment by shawnlan** [comment]
Still sees it.

**Comment by sfabriece** [comment]
I see the same, it is annoying.

```
"devDependencies": {
    "@ionic/app-scripts": "1.1.4",
    "typescript": "2.0.9"
  }
```

**Comment by sam-lex** [comment]
me too:
`"devDependencies": { "@ionic/app-scripts": "1.1.3", "typescript": "2.0.9" },`

`[11:18:04]  error opening ws message: {"category":"console","type":"log","data":["Log level is: ",5]}`
`[11:18:04]  error opening ws message: {"category":"console","type":"log","data":["DEVICE READY FIRED AFTER",1568,"ms"]}`

**Comment by stirumala76** [comment]
same here  with  "devDependencies": {
    "@ionic/app-scripts": "1.0.0",
    "typescript": "2.0.9"
  },

error opening ws message: {"category":"console","type":"info","data":["Ionic Storage
driver:","asyncStorage"]}

**Comment by shamank** [comment]
Same here debugging to phone:

$ ionic run android -l -c --target blabla
...
[23:25:16]  error opening ws message: {"category":"console","type":"log","data":["DEVICE READY FIRED AFTER",5603,"ms"]} 
[23:25:16]  error opening ws message: {"category":"console","type":"info","data":["Ionic Storage 
            driver:","asyncStorage"]} 
[23:25:16]  error opening ws message: {"category":"console","type":"info","data":["Ionic Storage 
            driver:","asyncStorage"]} 
[23:25:16]  error opening ws message: {"category":"console","type":"info","data":["Ionic Storage 
            driver:","asyncStorage"]} 
[23:25:16]  error opening ws message: {"category":"console","type":"info","data":["Ionic Storage 
            driver:","asyncStorage"]}
