### ISSUE TITLE
No provider for Storage!

### ISSUE THREAD

**Issue by gforster1993** [driftyco/ionic-storage#55]
Hey,

Great work with Ionic 2 guys. I've imported and injected the ionic-storage export (`{ Storage } from '@ionic/storage'`) as a provider in NgModule. I've then imported it and DI it into a service. The problem is, as well as injecting this service into any component which uses it, we are also having to import Storage as well.

Does anyone know why this would be the case?

Thanks

**Comment by shawnlauzon** [comment]
That sounds right.

In my file `LocalStorageProvider` which accesses storage, I have:

`import { Storage } from '@ionic/storage';`

And then in `app.module.ts`:

    import { Storage } from '@ionic/storage';
    import { LocalStorageProvider } from '../providers/local-storage';

    @NgModule({
      providers: [
        Storage,
        LocalStorageProvider,
        ...

**Comment by maitham1** [comment]
In our app.module.ts we have the following. 


```
` import {ProfileService} from '../providers/profile.service';
import {Storage} from '@ionic/storage';
@NgModule({
  providers: [
    Storage,
    ProfileService,
    ...
```

However for any page that utilises the profileService, where we run the following 

 ```
import {Storage} from '@ionic/Storage'
constructor(private af: AngularFire, public storage:Storage) {
    af.auth.subscribe(state => {
      if (!state) {
        return;
      }
      this.storage.set('userUID', state.uid);...
```

We are getting an error` main.js:51716 ORIGINAL EXCEPTION: No provider for Storage!`

Struggling to understand why ?

**Comment by gforster1993** [comment]
The issue was on our end. We were declaring the services in each page and not module wide. Fixed now, thanks @shawnlauzon. Closing issue.
