### ISSUE TITLE
Cannot find module "localforage"

### ISSUE THREAD

**Issue by NBAMj** [driftyco/ionic-storage#67]
I'm getting this error: `Cannot find module "localforage"`

I followed the tutorial from ionic page: https://ionicframework.com/docs/v2/storage/ 
without installing `SQLite` plugin.

This is my environment: 
```
Ionic Framework: 2.0.0-rc.5
Ionic Native: 2.2.11
Ionic App Scripts: 1.0.0
Angular Core: 2.2.1
Angular Compiler CLI: 2.2.1
```

**Comment by Gpzim98** [comment]
I'm struggling with the same problem following the official tutorial

**Comment by pabloim1** [comment]
Same here, any advance on this?

**Comment by felixble** [comment]
Have you tried removing the `@ionic/storage` package and re-install it again? That worked for me:

```
npm uninstall --save @ionic/storage
npm install --save @ionic/storage
```

**Comment by mhartington** [comment]
Hi there :smile: !  

I'm going to close this issue since it has been a while and chances are it's already been addressed. If you're still having troubles, please open a **new** issue. 
Thanks.

**Comment by otonielguajardo** [comment]
Same here :(

Ionic Framework: 2.3.0
Ionic App Scripts: 1.1.4
Angular Core: 2.4.8
Angular Compiler CLI: 2.4.8
Node: 6.10.1

Error: Cannot find module "localforage"
    at v (http://localhost:8100/build/polyfills.js:3:4864)
    at Object.<anonymous> (http://localhost:8100/build/main.js:115364:7)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
...

re-installing @ionic/storage didn't solve it.

What could be the source of this problem?

**Comment by mounthief** [comment]
Hello,

Please try :
npm install --save localforage
npm install --save localforage-cordovasqlitedriver

Hope it helps :)

**Comment by edmundo096** [comment]
Anyone landing here after some Googling...
This "may" be due `npm 5.5.1` as mentioned on issue #128 (which references a newer ionic version, `3.8.0`).

On my case, I updated to `npm 5.6.0` instead and still got same issue after removing `node_modules` and reinstalling.

But **my error was not removing the** `package-lock.json`.
After removing it along with `node_modules` and reinstalling, I finally got the app "serving" again.

Anyone landing here should check #128 for newer ionic version possible solutions (if any).

**Comment by beardedprince** [comment]
@mounthief 

![image](https://user-images.githubusercontent.com/30920382/47496665-7282f080-d84f-11e8-9df4-e292cbb2de9e.png)

I still get this error when i this

> Hello,
> 
> Please try :
> `npm install --save localforage`
> `npm install --save localforage-cordovasqlitedriver`
> 
> Hope it helps :)
