### ISSUE TITLE
rxjs@5.0.0-beta.12 does not satisfy its siblings' peerDependencies requirements!

### ISSUE THREAD

**Issue by aftab0000** [driftyco/ionic-storage#68]
I was getting peer dependencies error (Peer @angular/core@2.4.4 wants rxjs@^5.0.1) when I tried npm install. I found out in the package.json @angular/code version is "^2.0.0" which is actually installing @angular/code version 2.4.4. On the other hand rxjs is referred as "rxjs": "5.0.0-beta.12" which installing exactly 5.0.0-beta.12 version. And angular/core@2.4.4 is not compatible with rxjs@5.0.0-beta.12. 

I changed to rxjs reference to  "rxjs": "^5.0.0-beta.12" and it get fixed. 

Another thing I like to highlight here is because of this error I think other git project use ionic-storage is having the same issue. Like Ionic 2 seed project also getting the same issue. https://forum.ionicframework.com/t/npm-update-fails-with-hello-world-app/76199

**Comment by tobiasmuecksch** [comment]
This issue can be closed I guess?

**Comment by jgw96** [comment]
Hello, everyone! This has since been fixed (:
