### ISSUE TITLE
Missing key returns null

### ISSUE THREAD

**Issue by Kobzol** [driftyco/ionic-storage#7]
If I try to `get` a key that doesn't exist, `null` is returned. In older versions of the Storage Ionic plugin, `undefined` was returned, which I think is more appropriate. Is this by design?

**Comment by msio777** [comment]
+1

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This is actually an implementation detail of localForage, the library underneath ionic-storage. We could change this to where it does returns undefined if it gets a `null` from localForage, but im not entirely sure it would be worth the extra code and it could possibly cause other issues. Im gonna go ahead and leave this open to discussion.

**Comment by mhartington** [comment]
Closing since this how localforage works
