### ISSUE TITLE
 Error: Can't resolve all parameters for Storage: (?, ?).

### ISSUE THREAD

**Issue by goleary** [driftyco/ionic-storage#71]
I'm using @ionic/storage in a non-ionic Angular2 Project.  I never noticed this error when using it with Ionic, but I have now seen it while starting 2 Angular2 Projects that make use of the lib.

`Error: Can't resolve all parameters for Storage: (?, ?).`

I see this runtime error when my app.module.ts is set up as follows:

```
...
import { Storage } from '@ionic/storage';
@NgModule({
  providers: [
    Storage,
    ...
  ],
  ...
})
export class AppModule{ }
```
If I use a custom provider with no special values like this:
```
...
import { Storage } from '@ionic/storage';
export function provideStorage() {
 return new Storage();
}
@NgModule({
  providers: [
        { provide: Storage, useFactory: provideStorage },
    ...
  ],
  ...
})
export class AppModule{ }
```
then everything works no problem.  Is this to be expected? From reading the Documentation it doesn't seem like this should be necessary (and isn't in my separate Ionic App).

environment details:

```
angular-cli: 1.0.0-beta.25.5
node: 6.9.3
os: win32 x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5
@ionic/storage: 1.1.7
```

**Comment by nfantone** [comment]
Same problem here, on an Ionic app.

```sh
Error: Can't resolve all parameters for Storage: (?, ?).
Ionic Framework: 2.0.0
Ionic Native: 2.4.1
Ionic App Scripts: 1.0.0
Angular Core: 2.4.5
Angular Compiler CLI: 2.4.5
Node: 7.4.0
OS Platform: macOS Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.2996.0 Safari/537.36
```

**Comment by haschu** [comment]
Same here.

**Comment by haschu** [comment]
Turns out to be a bug within `@ionic/storage` 1.1.7. To solve this open your `package.json` and replace `"@ionic/storage": "^1.1.7"` with  `"@ionic/storage": "1.1.6"`.

https://forum.ionicframework.com/t/cannot-resolve-all-parameters-for-storage-make-sure-that-all-the-parameters-are-decorated-with-inject-or-have-valid-type-annotations-and-that-storage-is-decorated-with-injectable/47594/4

**Comment by rapropos** [comment]
I think the README should be modified somehow to indicate that simply listing `Storage` in the providers array is not guaranteed to work any more, and that the more elaborate `useFactory` approach documented under the "Configuring Storage (new in 1.1.7)" section is mandatory, even if it is as simple as:

```
{provide: Storage, useFactory: () => new Storage()},
```

I believe something in angular-cli changed somewhere between 2.2 and 4.0.0-beta.5 (perhaps with respect to optional parameters), and this is going to start biting people in droves. I tried adding `@Optional` decorators, but it did not seem to help.

**Comment by alx-andru** [comment]
@rapropos Thanks for your mention
[README configuring-storage-new-in-117](https://github.com/driftyco/ionic-storage/blob/master/README.md#configuring-storage-new-in-117
) was pure gold, worked perfect

**Comment by jgw96** [comment]
Hello all, this is now fixed in the new 2.0.0 release 🎉. Instructions [here](https://github.com/driftyco/ionic-storage/releases/tag/v2.0.0) on how to update.

**Comment by mohamedsharaf** [comment]
@jgw96 what about providers depends on Storage

`        {provide: Settings, useFactory: provideSettings, deps: [Storage]},
`

**Comment by matudelatower** [comment]
@jgw96 thanks, works for me

**Comment by mohamedsharaf** [comment]
```
export function provideStorage() {
    return new Storage();
    // return new Storage(['sqlite', 'websql', 'indexeddb'], { name: '__mydb' } /* optional config */);
}

        { provide: Storage, useFactory: provideStorage },

```
this works hope helps someone

**Comment by LiveListMobile** [comment]
thanks @mohamedsharaf . Your solution is the only one that worked for me. I've been stuck on this for several hours.

**Comment by rapropos** [comment]
@LiveListMobile if you're using ionic-storage 2.0, you should not be needing that strategy. Chances are you are still listing `Storage` in a providers array somewhere. You need to get rid of all of those.

**Comment by LiveListMobile** [comment]
@rapropos - I must be missing something (which is likely because I am new to Ionic2 and Ng).
1) I this morning I started a new **"tabs"** project to test the code.
2) I followed this: https://github.com/driftyco/ionic-storage/releases/tag/v2.0.0  to the letter. The only possible mistake is that I ran the npm install in my project folder (frontendprojects\myApp). Maybe that is wrong?
**app.module.ts**
`import { NgModule, ErrorHandler } from '@angular/core';
import { IonicApp, IonicModule, IonicErrorHandler } from 'ionic-angular';
import { IonicStorageModule } from '@ionic/storage';
import { MyApp } from './app.component';
import { AboutPage } from '../pages/about/about';
import { ContactPage } from '../pages/contact/contact';
import { HomePage } from '../pages/home/home';
import { TabsPage } from '../pages/tabs/tabs';
@NgModule({
  declarations: [
    MyApp,
    AboutPage,
    ContactPage,
    HomePage,
    TabsPage
  ],
  imports: [
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    AboutPage,
    ContactPage,
    HomePage,
    TabsPage
  ],
  providers: [{provide: ErrorHandler, useClass: IonicErrorHandler}]
})
export class AppModule {}`
3) And in my home.ts of the tabs template:
**home.ts**
`import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import { Storage } from '@ionic/storage';
@Component({
  selector: 'page-home',
  templateUrl: 'home.html',
  providers: []
})
export class HomePage {
  constructor(public navCtrl: NavController, storage: Storage) {
    storage.ready().then(() =>{
      storage.set('name', 'Alan the developer');
    });
  } // constructor
} // class`

I am still getting the following error belowr. I have tried all sorts of things but can't seem to get it right. Help?
![screenshot 2017-03-13 12 31 34](https://cloud.githubusercontent.com/assets/2897879/23867221/3a244c76-07e9-11e7-8d2c-b2f25ac0646c.png)

**Comment by rapropos** [comment]
@LiveListMobile this discussion is better suited for [the support forums](https://forum.ionicframework.com/) at this point, but I don't see you including the storage module in your app module's imports array.

**Comment by NoNameProvided** [comment]
@LiveListMobile putting your code snippets between triple backslashes will format them correctly.

```
example line1
example line2
```

**Comment by LiveListMobile** [comment]
@rapropos thank you. your sharp eyes caught the problem.
@NoNameProvided thanks as well. I will keep in mind for next time.

**Comment by nornes** [comment]
Where do you put the code in your solution, @mohamedsharaf? I have the same problem now.

**Comment by goleary** [comment]
@nornes if you look at the first post of this issue (scroll to top) you will see how and where you need to include that code.

**Comment by nornes** [comment]
@goleary Thank you

**Comment by rapropos** [comment]
@nornes If you are using ionic-storage 2.0, you are better off ignoring every single comment in this issue except for the one that closed it.

**Comment by LiveListMobile** [comment]
@nornes - @rapropos is correct.

**Comment by arturalkaim** [comment]
Hi
I'm having `Can't resolve all parameters for Storage: (?).` after update to ionic-storage 2.0.0
Any help regarding this issue?

**Comment by CelineBateauKessler** [comment]
@arturaalkaim, as mentioned by @jgw96, follow instructions https://github.com/driftyco/ionic-storage/releases/tag/v2.0.0 and it's OK.

**Comment by aliridha1510** [comment]
@arturalkaim   https://ionicframework.com/docs/storage/

**Comment by hsuDev** [comment]
import { ErrorHandler, NgModule } from '@angular/core';
import { IonicApp, IonicErrorHandler, IonicModule } from 'ionic-angular';
import {Storage} from "@ionic/storage";

import { MyApp } from './app.component';
import { HomePage } from '../pages/home/home';
import {NewPlacePage} from "../pages/new-place/new-place";
import {PlacesService} from "../pages/services/places.services";



@NgModule({

  declarations: [
    MyApp,
    HomePage,
    NewPlacePage
  ],
  imports: [
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    HomePage,
    NewPlacePage
  ],
  providers: [{provide: ErrorHandler, useClass: IonicErrorHandler}, PlacesService, Storage]
})
export class AppModule {}


//same issue in mine... above is the cord

the error comes is
Runtime Error
Can't resolve all parameters for Storage: (?).
Stack
Error: Can't resolve all parameters for Storage: (?).
    at syntaxError (http://localhost:8100/build/main.js:76132:34)
    at CompileMetadataResolver._getDependenciesMetadata (http://localhost:8100/build/main.js:89469:35)
    at CompileMetadataResolver._getTypeMetadata (http://localhost:8100/build/main.js:89337:26)
    at CompileMetadataResolver._getInjectableMetadata (http://localhost:8100/build/main.js:89323:21)
    at CompileMetadataResolver.getProviderMetadata (http://localhost:8100/build/main.js:89613:40)
    at http://localhost:8100/build/main.js:89542:49
    at Array.forEach (native)
    at CompileMetadataResolver._getProvidersMetadata (http://localhost:8100/build/main.js:89503:19)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:8100/build/main.js:89158:50)
    at JitCompiler._loadModules (http://localhost:8100/build/main.js:100222:66)



Ionic Framework: 3.3.0
Ionic App Scripts: 1.3.7
Angular Core: 4.1.2
Angular Compiler CLI: 4.1.2
Node: 6.10.3
OS Platform: Windows 8.1
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.12.2987.98 Safari/537.36

please helpme

**Comment by matudelatower** [comment]
@hsuDev try to use like StorageModule described in http://ionicframework.com/docs/storage/

check https://github.com/MisPlaces/app/blob/master/src/app/app.module.ts#L71

in your case: 

```typescript
import { ErrorHandler, NgModule } from '@angular/core';
import { IonicApp, IonicErrorHandler, IonicModule } from 'ionic-angular';
import { IonicStorageModule } from "@ionic/storage"; //<-add this

import { MyApp } from './app.component';
import { HomePage } from '../pages/home/home';
import {NewPlacePage} from "../pages/new-place/new-place";
import {PlacesService} from "../pages/services/places.services";

@NgModule({

declarations: [
MyApp,
HomePage,
NewPlacePage
],
imports: [
IonicModule.forRoot(MyApp),
IonicStorageModule.forRoot({
      name: '__yourappname',
      driverOrder: ['indexeddb', 'sqlite', 'websql']
    }) //<-add this
],
bootstrap: [IonicApp],
entryComponents: [
MyApp,
HomePage,
NewPlacePage
],
providers: [{provide: ErrorHandler, useClass: IonicErrorHandler}, PlacesService]
})
export class AppModule {}
```

**Comment by cocomo** [comment]
Please: I see a similar error when I try to create Storage from a ReflectiveInjector:

> Error: Cannot resolve all parameters for 'Storage'(?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'Storage' is decorated with Injectable. — core.es5.js:1392

My injection works like this:

```
var injector = ReflectiveInjector.resolveAndCreate([
                UserProvider, 
                UserSession,
                LocalStorage,
                //forwardRef(() => Storage), // Storage, // not in the injector?
                // @Inject(forwardRef(() => Storage)) storage: Storage
                Storage,
                //{provide: Storage, useClass: Storage}, …

```
I read the documentation and followed the instructions in this issue but could not find anything about manual storage injection.

**Comment by karlpatrickespiritu** [comment]
Just solved my issue of `Can't resolve all parameters for Storage: (?).`.

After hours of searching, I found out that I had a component that had `Storage` as a provider. So what I did was removed it.

````javascript
@Component({
  selector: 'login',
  templateUrl: 'login.component.html',
  providers: [
    AuthService,
    // Storage, <-- removed this one
    JwtHelper
  ]
})
````

**Comment by bruno-py** [comment]
Placing an @Injectable() decorator to the class where I'm making use of the Storage service fixed for me.
Shouldn't that be specified on the the documentation example?

**Comment by jgfet** [comment]
My app had been working with local storage for ages.
I did some refactoring on page A, then suddenly got error for page B.
To solve issue I did this in Page B:
   @Inject(forwardRef(() => KeyValueService ))
    private kvs:KeyValueService,

kvs:KeyValueService was the ? in the parameters for page B.
That solved it.

**Comment by elbakly** [comment]
Here is how we managed to pass the issue  we did not passing it to the instructor at all but declaring it with in the constructor function 
```js
import {CartStorage} from '../../providers/cartstorage';
export class HomePage {
cart;
constructor(){
this.cart=CartStorage;
}

}
```

**Comment by richie50** [comment]
@matudelatower  nice clean solution.
