### ISSUE TITLE
Should we be worried?

### ISSUE THREAD

**Issue by cozzbie** [driftyco/ionic-storage#76]
So basically this is two questions in one. Not sure if I should be worried because these two all of sudden seem to coincide. For the second image, I am trying this on iOS 10. I had no errors before and now this. Any ideas?

![screen shot 2017-02-09 at 9 01 34 pm](https://cloud.githubusercontent.com/assets/3672236/22800902/2f49f2c0-ef0b-11e6-8704-30747b56d83e.png)

<---------------------------------------------------------------------------------------------->

![screen shot 2017-02-09 at 9 03 52 pm](https://cloud.githubusercontent.com/assets/3672236/22800949/578ae906-ef0b-11e6-92c0-5d1c2bb6bc4e.png)

**Comment by NoNameProvided** [comment]
It works for me.

If you got no other errors than this, then I guess you are trying to reach `this.storage` somewhere where it wasn't injected.
