### ISSUE TITLE
Update Ionic-storage Readme.md for version 2.0.0

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/ionic-storage#83]
Hi,

I just noticed that the Readme.md of Ionic-storage isn't updated with the installation and configuration guidelines relative to version 2.0.0, thought I gonna leave a note about that.

Respectively like described there: https://github.com/driftyco/ionic-storage/releases/tag/v2.0.0

Thx in advance for the update

**Comment by wezzcoetzee** [comment]
Hi

In the interim, you can follow the comments [HERE](https://github.com/driftyco/ionic-storage/compare/v2.0.0...master#diff-89e9fd90feb499cac1623bd562b7c8e3)

**Comment by AndreasGassmann** [comment]
I made a pull request with an updated readme: https://github.com/driftyco/ionic-storage/pull/85
