### ISSUE TITLE
inside app.modules

### ISSUE THREAD

**Issue by abomadi** [driftyco/ionic-storage#86]
how to call it inside app.modules
im trying this but not working on the newer version

```
import { IonicStorageModule, Storage } from '@ionic/storage';

let storage: Storage = new Storage();
```

i need to bring data from storage for angular-jwt options token getter

**Comment by NoNameProvided** [comment]
Follow the setup instructions in the README file or the original [docs](https://ionicframework.com/docs/v2/storage/).

**Comment by abomadi** [comment]
Fixed by removing Storage from Providers section inside app.modules
