### ISSUE TITLE
README and Docs for 2.0.0 are incorrect

### ISSUE THREAD

**Issue by findel** [driftyco/ionic-storage#87]
The instructions for the 2.0.0 release (https://github.com/driftyco/ionic-storage/releases/tag/v2.0.0) specifically state that 'Storage' needs to be removed from app.module.ts

But the docs (https://ionicframework.com/docs/v2/storage/) and the README say otherwise.

**Comment by conara** [comment]
Thanks!

**Comment by amandeepmittal** [comment]
The docs have been updated, so this issue can be closed?
