### ISSUE TITLE
A lot of warnings in Xcode regarding a SQLlite

### ISSUE THREAD

**Issue by 0x1ad2** [driftyco/ionic-storage#90]
I included Ionic storage in my application but I'm getting a lot of errors when building in Xcode.

**Your system information:**
>Cordova CLI: 6.5.0 
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.2.1 Build version 8C1002

**[Xcode warnings]**

**User-Defined Issue Group**
>/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:29299:6: "gethostuuid() is disabled."

**Lexical or Preprocessor Issue Group**
>/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:25233:13: Ambiguous expansion of macro 'MAX'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:25235:32: Ambiguous expansion of macro 'MAX'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:60450:43: Ambiguous expansion of macro 'MAX'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:64898:16: Ambiguous expansion of macro 'MIN'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:68195:21: Ambiguous expansion of macro 'MIN'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:68496:18: Ambiguous expansion of macro 'MIN'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:69665:44: Ambiguous expansion of macro 'MAX'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:74538:22: Ambiguous expansion of macro 'MIN'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:74566:22: Ambiguous expansion of macro 'MIN'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:74745:12: Ambiguous expansion of macro 'MIN'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:82014:42: Ambiguous expansion of macro 'MAX'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:85382:18: Ambiguous expansion of macro 'MAX'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:85662:24: Ambiguous expansion of macro 'MIN'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:85844:17: Ambiguous expansion of macro 'MIN'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:85845:28: Ambiguous expansion of macro 'MAX'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:86845:19: Ambiguous expansion of macro 'MAX'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:87293:21: Ambiguous expansion of macro 'MIN'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:87723:17: Ambiguous expansion of macro 'MIN'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:87830:22: Ambiguous expansion of macro 'MIN'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:88017:10: Ambiguous expansion of macro 'MAX'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:96540:18: Ambiguous expansion of macro 'MAX'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:96571:18: Ambiguous expansion of macro 'MAX'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:96634:20: Ambiguous expansion of macro 'MAX'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:101740:15: Ambiguous expansion of macro 'MIN'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:113020:22: Ambiguous expansion of macro 'MAX'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:125768:19: Ambiguous expansion of macro 'MAX'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:125775:19: Ambiguous expansion of macro 'MAX'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:128535:14: Ambiguous expansion of macro 'MIN'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:130062:10: Ambiguous expansion of macro 'MIN'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:131710:19: Ambiguous expansion of macro 'MIN'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:154439:11: Ambiguous expansion of macro 'MIN'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:157300:14: Ambiguous expansion of macro 'MIN'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:157435:37: Ambiguous expansion of macro 'MAX'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:157457:43: Ambiguous expansion of macro 'MAX'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:158023:37: Ambiguous expansion of macro 'MAX'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:163120:26: Ambiguous expansion of macro 'MIN'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:163121:28: Ambiguous expansion of macro 'MAX'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:163125:26: Ambiguous expansion of macro 'MIN'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:163126:28: Ambiguous expansion of macro 'MAX'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:163175:12: Ambiguous expansion of macro 'MAX'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:163176:12: Ambiguous expansion of macro 'MIN'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:164375:27: Ambiguous expansion of macro 'MAX'

**Value Conversion Issue Group**
>/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:30675:14: Implicit conversion loses integer precision: 'ssize_t' (aka 'long') to 'int'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:32365:42: Implicit conversion loses integer precision: 'unsigned long long' to 'int'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:32510:11: Implicit conversion loses integer precision: 'ssize_t' (aka 'long') to 'int'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:32577:35: Implicit conversion loses integer precision: 'long long' to 'int'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:33835:33: Implicit conversion loses integer precision: 'long long' to 'int'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:35451:17: Implicit conversion loses integer precision: 'ssize_t' (aka 'long') to 'int'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:35582:17: Implicit conversion loses integer precision: 'ssize_t' (aka 'long') to 'int'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:35893:11: Implicit conversion loses integer precision: 'unsigned long' to 'int'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:35901:11: Implicit conversion loses integer precision: 'unsigned long' to 'int'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:36194:19: Implicit conversion loses integer precision: 'ssize_t' (aka 'long') to 'int'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:36357:37: Implicit conversion loses integer precision: 'unsigned long' to 'int'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:36572:53: Implicit conversion loses integer precision: 'unsigned long' to 'int'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:76566:42: Implicit conversion loses integer precision: 'sqlite3_uint64' (aka 'unsigned long long') to 'int'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:80163:21: Implicit conversion loses integer precision: 'i64' (aka 'long long') to 'int'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:86681:47: Implicit conversion loses integer precision: 'long' to 'int'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:87764:40: Implicit conversion loses integer precision: 'long long' to 'int'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:87854:23: Implicit conversion loses integer precision: 'long long' to 'int'
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:159003:55: Implicit conversion loses integer precision: 'long' to 'u32' (aka 'unsigned int')

**Semantic Issue Group**
>/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:128735:39: Code will never be executed
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:128679:39: Code will never be executed
/Users/dennisbruijn/Projects/<project_folder>/platforms/ios/<app_name>/Plugins/cordova-sqlite-storage/sqlite3.c:135078:9: Code will never be executed

**Comment by mhartington** [comment]
So this is definitely an issue on the sqlite plugin side of things. Since Ionic storage itself doesn't include any native code, the culprit here would be 

https://github.com/litehelpers/Cordova-sqlite-storage

Since these are just "warnings" and not full errors, there's no harm right now, just looks scary. 
But this might cause issues when Apple updates the ios sdk.
But the correct place to report these warnings would be the sqlite plugin repo.
