### ISSUE TITLE
how to update existing object value on storage

### ISSUE THREAD

**Issue by bhumin3i** [driftyco/ionic-storage#92]
Hi, 
i'm using angular 2 storage, i want to update existing object value but i can't update.

i'm using below methods 
//for get compaint
 getCompaintData() {
    return this.storage.get('compaint');  
  }
//save compaint 
  saveCompaintData(data){
    let newData = JSON.stringify(data);
    this.storage.set('compaint', newData);
  }
//update complaint data
// data include object 

   updateCompaintData(data){
     let returnStatus:boolean = false;
    this.storage.get('compaint').then((complaintsDatas) => {
      if (complaintsDatas) {
        let complaints = JSON.parse(complaintsDatas);
            for(let i=0; i < complaints.length;i++){
              if(complaints[i].id == data.id){
                console.log('append',data.resolveComment);
                complaints[i].resolveComment = data.resolveComment;
                 returnStatus = true;
                  let newData = JSON.stringify(complaints);
                this.storage.set('compaint', newData);
              }
          }
      }
    });
    return returnStatus;
  }

for example my 
ComplaintData = 
{"id":1,"name":"Bhumin","email":"bhumin@3i","companyName":"3i-info","mobileNo":"90231221212","complaintRegarding":"company name rergister","complaintText":"company name is going to be change","isResolve":false,"resolveComment":"","addDate":"2017-03-21T06:27:51.326Z"},{"id":2,"name":"Manjoj","email":"manoj@3i","companyName":"3i-info","mobileNo":"98908909898","complaintRegarding":"comapny name register","complaintText":"want to change company name","isResolve":false,"resolveComment":"","addDate":"2017-03-21T06:30:21.341Z"}

i want to update resolveComment of row 0 but i can't update it how do they do it?

**Comment by ghenry22** [comment]
it's basically get the value, change it, then set it back with the ionic-storage plugin.

If you want more flexibility to query the data store and directly update records etc then you can use the cordova sqlite plugin functionality through ionic-native instead of using ionic-storage.

I tend to read all values from the storage on start up, deal with them in memory while the app is live and just re-persist them to the store whenever I change something.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
