### ISSUE TITLE
.get() resolves and returns null

### ISSUE THREAD

**Issue by louisdoe** [driftyco/ionic-storage#94]
Hi

I explicitly "remove" the variable "user" from Storage, but .get still return a resolved Promise, with value = null.
Can you help please ?
Thanks

               this.storage.ready().then(() => {
			return this.storage.remove('user').then( () => {
				return this.storage.get('user');
			})
		})
		.then(val => {
    		console.log("user is in Storage:", val);
    		this.splashScreen.hide();
		})
		.catch(e =>  {
			//we don't have the user data so we will ask him to log in
    		this.nav.push(LoginPage);
    		this.splashScreen.hide();
		});

in the console.log:  `user is in Storage: null`.

$ ionic info

Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v7.4.0
Xcode version: Not installed

$ npm list | grep "storage"
├─┬ @ionic/storage@2.0.1
│ ├── @types/pouchdb-adapter-localstorage@5.4.4
├── angular-2-local-storage@1.0.1

**Comment by oddcb** [comment]
Ionic Storage is using localForage as far as I know. According to the api docs at https://localforage.github.io/localForage/#data-api-getitem the behaviour is correct. 

getItem:
>Gets an item from the storage library and supplies the result to a callback. If the key does not exist, getItem() will return null.

**Comment by louisdoe** [comment]
Yes indeed you're right! 
Thank you
