### ISSUE TITLE
why is call to `ready()` necessary?

### ISSUE THREAD

**Issue by goleary** [driftyco/ionic-storage#96]
It seems like this should be an internal only function that `get()`, `set()` etc. should be calling before returning.

In some of my components I  am writing functions like:

    getFromStorage(key: string){
      return this.storage.ready().then(()=>this.storage.get(key));
    }

This seems like the kind of thing that it doesn't make sense for users (of ionic-storage) to have to do.

**Comment by NoNameProvided** [comment]
Now you can use this packages as standalone and I think the reason behind not calling `ready() internally is the need to bundle ionic-native with ionic-storage in that case.

**Comment by goleary** [comment]
What would require ionic-native to be packaged as well? I don't see anything in the code that suggests that...

**Comment by NoNameProvided** [comment]
Ahh sorry I have misread your issue, I thought you are talkinb about the Ionic's `platform.ready()` call.

**Comment by tabirkeland** [comment]
I'm curious about this as well.  Every method on the `Storage` class returns the `this._dbPromise`, so it seems a little redundant to call `ready()` before calling any of the public methods.

**Comment by Sliverb** [comment]
I second
